version: "3.3"

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
