version: "3.3"

volumes: 
  mongo:

services:
  mongodb:
    image: mongo:4.4.4-bionic
    volumes:
      - mongo:/var/lib/mongo
    ports:
      - localhost:27018:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always
