export enum Status {
  ACCEPTED = 'ACCEPTED',
  RFC = 'RFC',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
  OBSOLETE = 'OBSOLETE',
  FORMAL_SUBMISSION = 'FORMAL SUBMISSION',
}

export enum StatusType {
  ACCEPTED = 'ACCEPTED',
  RFC = 'RFC',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
  OBSOLETE = 'OBSOLETE',
  FORMAL_SUBMISSION = 'FS',
  DEFAULT = 'DEFAULT',
  EMPTY = 'EMPTY',
}
