export enum Env {
  MongoDBUri = "MONGODB_URI",
  Port = "PORT",
  FolderRepositoryName = "FOLDER_REPOSITORY_NAME",
  RepoPath = "REPO_PATH",
  RepoBranch = "REPO_BRANCH",
  FolderPattern = "FOLDER_PATTERN",
  WebhooksSecretToken = "WEBHOOKS_SECRET_TOKEN",
  GitAccessApiToken = "GIT_ACCESS_API_TOKEN",
  GithubUrlApiEndpoint = "GITHUB_URL_API_ENDPOINT",
  GithubRepository = "GITHUB_REPOSITORY",
  GithubRepositoryOwner = "GITHUB_REPOSITORY_OWNER",
  GithubLinks = "GITHUB_LINKS",
  GithubRepositoryId = "GITHUB_REPOSITORY_ID",
}
